 
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author niru
 */

public class Vendor extends javax.swing.JInternalFrame {

    /**
     * Creates new form Vendor
     */
    Connection con=null;
    String vendor;
    Statement st1;
    String d = null;
    public Vendor() {
        initComponents();
        jPanel2.setVisible(false);
        jButton2.setVisible(false);
            java.util.Date dnow= new java.util.Date();
            SimpleDateFormat ft= new SimpleDateFormat("yyyy.MM.dd");
            d=ft.format(dnow.getTime());
            jTextField4.setText(d);
            int rowCount =1;
                try{
                String s1=new String("V0");
                con=ConnectionProvider.getConnection();
                st1=con.createStatement();
                ResultSet rs=st1.executeQuery("select Vendorid from newvendor");
                 while (rs.next()) {
                   vendor = rs.getString(1);
                   rowCount++;
            }
                 System.out.println("vendor takes max data "+vendor);
                 System.out.println("rowCount= "+rowCount);
                 Integer intobj=new Integer(rowCount);
                  jTextField5.setText(s1.concat(intobj.toString()));
           }
           catch(Exception e)
                {
                    System.err.println(e.getMessage());
           //     JOptionPane.showMessageDialog(null, "Your Vendor ID is Duplicate='"+ jTextField5.getText() +"'");                        
                }
            //jLabel1.requestFocusInWindow();
    jTextField1.setVisible(false);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Add Vendor");

        jLabel1.setText("Vendor ID");

        jLabel3.setText("Name");

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });

        jLabel4.setText("Contact No.");

        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.lightGray));
        jPanel2.setName("Service"); // NOI18N

        jCheckBox1.setText("Engine Oil");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("Oil Filter");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setText("Air Filter");

        jCheckBox4.setText("Diesel Filter");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        jCheckBox5.setText("Wiper");

        jCheckBox6.setText("Break Parts");

        jCheckBox7.setText("Power Steering");

        jCheckBox8.setText("Gear oil");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });

        jCheckBox9.setText("Break oil");
        jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
            }
        });

        jCheckBox10.setText("Break shol");
        jCheckBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox10ActionPerformed(evt);
            }
        });

        jCheckBox11.setText("Horn");

        jCheckBox12.setText("Head Light Bulb");

        jCheckBox13.setText("Spark Plug");

        jCheckBox14.setText("Belts");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Parts");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Selected Item");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBox1)
                                            .addComponent(jCheckBox2)
                                            .addComponent(jCheckBox6))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jCheckBox3)
                                                .addGap(18, 18, 18)
                                                .addComponent(jCheckBox4))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jCheckBox9)
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jCheckBox8)
                                                    .addComponent(jCheckBox13)))
                                            .addComponent(jCheckBox10))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jCheckBox12)
                                                .addGap(18, 18, 18)
                                                .addComponent(jCheckBox14))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jCheckBox7)
                                                .addGap(18, 18, 18)
                                                .addComponent(jCheckBox11))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jCheckBox5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton2))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 45, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox12)
                    .addComponent(jCheckBox14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckBox9)
                        .addComponent(jCheckBox13)
                        .addComponent(jCheckBox7)
                        .addComponent(jCheckBox11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jCheckBox2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox6)
                    .addComponent(jCheckBox10)
                    .addComponent(jCheckBox8)
                    .addComponent(jCheckBox5)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel6.setText("Date");

        jTextField4.setEnabled(false);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
                addActionListener(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextField5.setEnabled(false);
        jTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField5FocusLost(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vendor.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(409, 409, 409)
                        .addComponent(jLabel2)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(274, 274, 274))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(51, 51, 51)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(76, 76, 76))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton1)))
                    .addComponent(jLabel7))
                .addGap(124, 124, 124)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void checkboxnull()
    {
          jCheckBox1.setSelected(false);
          jCheckBox2.setSelected(false);
          jCheckBox3.setSelected(false);
          jCheckBox4.setSelected(false);
          jCheckBox5.setSelected(false);
          jCheckBox6.setSelected(false);
          jCheckBox7.setSelected(false);
          jCheckBox8.setSelected(false);
          jCheckBox9.setSelected(false);
          jCheckBox10.setSelected(false);
          jCheckBox11.setSelected(false);
          jCheckBox12.setSelected(false);
          jCheckBox13.setSelected(false);
          jCheckBox14.setSelected(false);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String id=jTextField5.getText().trim();
        String name=jTextField2.getText().trim();
        String mobile=jTextField3.getText().trim();
        String date=jTextField4.getText().trim();
        //String item=jTextArea1.getText().trim();
        try
        {
        
        con=ConnectionProvider.getConnection();
        if(name.equals("")||mobile.equals(""))
        {
            javax.swing.JOptionPane.showMessageDialog(null,"These are compulsory to fill.");
        }
        else
        {
            PreparedStatement ps=con.prepareStatement("insert into newvendor values(?,?,?,?)");
            ps.setString(1, id);
            ps.setString(2, name);
            ps.setString(3, mobile);
            ps.setString(4, date);
            //ps.setString(5, item);
            ps.execute();
            javax.swing.JOptionPane.showMessageDialog(null, "Your Data Add is Successfully...");
        //    jTextField5.setText(null);
            jTextField2.setText(null);
            jTextField3.setText(null);
            jTextArea1.setText(null);
          //  jTextField5.setEnabled(true);
            jTextField2.setEnabled(true);
            jTextField3.setEnabled(true);
            checkboxnull();
        }
        }
        catch(Exception e)
        {
            System.err.println("Error" + e.getMessage());
            javax.swing.JOptionPane.showMessageDialog(null,"Duplicate Entry '"+ id+"'");
        }
                
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
            char key=evt.getKeyChar();
            int k=key;
            String aa=jTextField3.getText();
            int l=aa.length();
            if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'||k==KeyEvent.VK_BACK_SPACE||k==KeyEvent.VK_TAB||k==KeyEvent.VK_SPACE||k==KeyEvent.VK_ENTER||k==KeyEvent.VK_ALT)
            {
                jTextField3.setEditable(true);
            }
            else 
            {               
                jTextField3.setEditable(false);
                javax.swing.JOptionPane.showMessageDialog(null, "Enter only numeric digit(0-9)");
                //jLabel10.setText("* Enter only numeric digit(0-9)");
             }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained

        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1FocusGained

    private void addActionListener(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionListener

            
        // TODO add your handling code here:
    }//GEN-LAST:event_addActionListener

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
    String str="";
    str=jTextField3.getText();
    if(str.length()<10 || str.length()>12)
    {
        JOptionPane.showMessageDialog(null,"Phone No must be 10 to 12 Digits");
        jTextField3.setText("");
    }
        String phon="";
        phon=jTextField3.getText();
        try
        {
        con=ConnectionProvider.getConnection();
        Statement st=con.createStatement();
        ResultSet rs=st.executeQuery("select * from items where Contactno='"+phon+"'");
        if(rs.next())
        {
           
           JOptionPane.showMessageDialog(null, "Your Contactno is Duplicate='"+phon+"'");
           jTextField3.setText(null);
        }
        else
        {
           
        }
        
        }
        catch(Exception e)
        {
        System.out.println(e.getMessage());
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3FocusLost

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
 //         jTextField5.setText(null);
          jTextField2.setText(null);
          jTextField3.setText(null);
          jTextArea1.setText(null);
          //jTextField5.setEnabled(true);
          jTextField2.setEnabled(true);
          jTextField3.setEnabled(true);
          jButton1.setEnabled(true);
          checkboxnull();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
       
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        char key=evt.getKeyChar();
        int k=key;
        if(evt.getKeyChar()>='A' && evt.getKeyChar()<='Z'||k==KeyEvent.VK_SPACE  ||k==KeyEvent.VK_SHIFT)
        {
            
            jTextField2.setEditable(true);
            
            
        }
        else if(evt.getKeyChar()>='a' && evt.getKeyChar()<='z'||k==KeyEvent.VK_SPACE ||k==KeyEvent.VK_SHIFT)
        {
            jTextField2.setEditable(true);
            
        }
        else if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
            {
                jTextField2.setEditable(false);
                javax.swing.JOptionPane.showMessageDialog(null, "Only Alphabet");

            }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusLost

        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5FocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String s1 = "";
        //s1=jTextArea1.getText();

        if (jCheckBox1.isSelected()) {
            //jCheckBox1.setSelected(true);
            s1 = s1 + "" + jCheckBox1.getText() + ',' + " ";
            jTextArea1.setText(s1);
        } else {
            jCheckBox1.setSelected(false);
        }
        if (jCheckBox2.isSelected()) {
            s1 = s1 + "" + jCheckBox2.getText() + ',' + " ";
            jTextArea1.setText(s1);
        } else {
            jCheckBox2.setSelected(false);

        }
        if (jCheckBox3.isSelected()) {
            s1 = s1 + "" + jCheckBox3.getText() + ',' + " ";
            jTextArea1.setText(s1);
        } else {
            jCheckBox3.setSelected(false);
        }
        if (jCheckBox4.isSelected()) {
            s1 = s1 + "" + jCheckBox4.getText() + ',' + " ";
            jTextArea1.setText(s1);
        } else {
            jCheckBox4.setSelected(false);
        }
        if (jCheckBox5.isSelected()) {
            s1 = s1 + "" + jCheckBox5.getText() + ',' + " ";
            jTextArea1.setText(s1);
        } else {
            jCheckBox5.setSelected(false);
        }
        if (jCheckBox6.isSelected()) {
            s1 = s1 + "" + jCheckBox6.getText() + ',' + " ";
            jTextArea1.setText(s1);
        } else {
            jCheckBox6.setSelected(false);
        }
        if (jCheckBox7.isSelected()) {
            s1 = s1 + "" + jCheckBox7.getText() + ',' + " ";
            jTextArea1.setText(s1);
        } else {
            jCheckBox7.setSelected(false);
        }
        if (jCheckBox8.isSelected()) {
            s1 = s1 + "" + jCheckBox8.getText() + ',' + " ";
            jTextArea1.setText(s1);
        } else {
            jCheckBox8.setSelected(false);
        }
        if (jCheckBox9.isSelected()) {
            s1 = s1 + "" + jCheckBox9.getText() + ',' + " ";
            jTextArea1.setText(s1);
        } else {
            jCheckBox9.setSelected(false);
        }
        if (jCheckBox10.isSelected()) {
            s1 = s1 + "" + jCheckBox10.getText() + ',' + " ";
            jTextArea1.setText(s1);
        } else {
            jCheckBox10.setSelected(false);
        }
        if (jCheckBox11.isSelected()) {
            s1 = s1 + "" + jCheckBox11.getText() + ',' + " ";
            jTextArea1.setText(s1);
        } else {
            jCheckBox11.setSelected(false);
        }
        if (jCheckBox12.isSelected()) {
            s1 = s1 + "" + jCheckBox12.getText() + ',' + " ";
            jTextArea1.setText(s1);
        } else {
            jCheckBox12.setSelected(false);
        }
        if (jCheckBox13.isSelected()) {
            s1 = s1 + "" + jCheckBox13.getText() + ',' + " ";
            jTextArea1.setText(s1);
        } else {
            jCheckBox13.setSelected(false);
        }
        if (jCheckBox14.isSelected()) {
            s1 = s1 + "" + jCheckBox14.getText() + ',' + " ";
            jTextArea1.setText(s1);
        } else {
            jCheckBox14.setSelected(false);
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCheckBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox10ActionPerformed

    private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox9ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed



        // TODO add your handling code here:
 }//GEN-LAST:event_jCheckBox1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
